version: '3.9'

services:
  db:
    image: postgres:15.3
    container_name: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: paotooong
    volumes:
      - ./data:/var/lib/postgresql/data

