version: '3.9'

services:
  db:
    image: postgres:15.3
    container_name: db
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: paotooong
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432/tcp

